ARG PYTHON_VERSION=3.10
ARG DEBIAN_VERSION=bullseye

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION} AS builder

RUN pip install --user --no-cache-dir lxml==4.7.*

RUN chmod 755 /root/.local/lib/*/site-packages

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}
	
RUN apt-get update && apt-get install -y libxml2 libxslt1.1 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local/lib/ /usr/local/lib/
