ARG PYTHON_VERSION=3.9
ARG DEBIAN_VERSION=buster

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION} AS builder

RUN pip install --user --no-cache-dir lxml==4.6.*

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}
	
RUN apt-get update && apt-get install -y libxml2 libxslt1.1 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local/lib/ /usr/local/lib/
